version: '3.9'
services:
  postgres:
    image: postgis/postgis:15-3.5
    container_name: mapbox_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: mapbox_user
      POSTGRES_PASSWORD: mapboX123
      POSTGRES_DB: mapbox_db

    volumes:
      - ./src:/app

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mapbox_user -d mapbox_db"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data: